CREATE DATABASE IF NOT EXISTS houses_db;

CREATE TABLE IF NOT EXISTS readings(
    Reading_index INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Reading_date DATE,
    Address_ VARCHAR(255) NOT NULL,
    Balkon_ BOOL DEFAULT FALSE,
    Bijzonderheden_ VARCHAR(255),
    Bouwjaar_ INT,
    Broker_ VARCHAR(255),
    Energielabel_(geschat)_ VARCHAR(255),
    Energieverbruik_(geschat)_ VARCHAR(255),
    Garage_  BOOL DEFAULT FALSE,
    Geplaatst_op_ DATE,
    Huidige_vraagprijs_ VARCHAR(255),
    ID_ VARCHAR(255),
    Inhoud_ INT,
    Isolatie_ VARCHAR(255),
    Kamers_  INT,
    Keuken_ VARCHAR(255),
    Long_description_ TEXT,
    Oorspronkelijke_vraagprijs_ INT,
    Perceeloppervlakte_ INT,
    Pricetype_ VARCHAR(255),
    Sanitaire_voorzieningen_ VARCHAR(255),
    Short_description_ TEXT,
    Slaapkamers_ INT,
    Sold_ VARCHAR(255),
    Staat_onderhoud_ VARCHAR(255),
    Staat_schilderwerk_ VARCHAR(255),
    Tuin_ VARCHAR(255),
    Type_ VARCHAR(255),
    Uitzicht_ VARCHAR(255),
    Verwarming_ VARCHAR(255),
    Woonoppervlakte_ INT,
    Zip_ VARCHAR(255),
    ZipCode_ VARCHAR(255),
    Longitude_ FLOAT(1,8),
    Latitude_ FLOAT(2,7)
);

